@startuml
科室用户 -> 微信小程序: 打开
科室用户 <-- 微信小程序: 提示用户扫描设备标签的二维码
科室用户 -> 微信小程序: 用户开始扫描
微信小程序 -> 设备标签: 扫描标签二维码
微信小程序 <-- 设备标签: 获取设备ID
微信小程序 -> 服务器: 请求设备信息
服务器 --> 微信小程序: 设备相关数据
微信小程序 -> 微信小程序: 显示设备详情页面
科室用户 -> 微信小程序: 点击报修按钮
微信小程序 -> 微信小程序: 显示设备报修页面
科室用户 -> 微信小程序: 填写报修问题
alt 从常用问题列表中选择报修问题
    微信小程序 -> 微信小程序: 显示选中的常用问题对应的解决方法
end
科室用户 -> 微信小程序: 填写报修描述信息
科室用户 -> 微信小程序: 选择报修紧急程度
科室用户 --> 微信小程序: 预约维修时间段(默认任意工作时间)
科室用户 -> 微信小程序: 检查用户信息(科室,姓名,电话)
科室用户 -> 微信小程序: 添加设备问题相关照片(拍摄)
微信小程序 -> 服务器: 提交用户报修信息
微信小程序 <-- 服务器: 报修成功
微信小程序 --> 科室用户: 报修成功,等待派工
科室用户 -> 微信小程序: 返回我的报修
科室用户 <-- 微信小程序: 显示用户报修历史界面
@enduml