@startuml
participant 设备科主管 as zg
participant WEB端应用 as web
participant 服务器 as ser
participant 设备科工程师1 as gcs
participant 设备科工程师2 as gcso

web -> ser: 轮询事件信息
ser --> web: 报修事件提醒
zg <- web: 设备报修提醒
zg -> web: 查看设备报修
web -> ser: 获取医院设备报修信息
web <-- ser: 设备报修数据
web -> web: 显示设备报修列表
zg -> web: 选择报修信息
zg -> web: 点击派工按钮
web -> ser: 获取当前设备(品牌,类型,规格)可负责维护的设备科工程师列表
web <-- ser: 设备科工程师列表数据
web -> web: 显示当前可用工程师列表
zg -> web: 选择派工工程师
zg -> web: 确认派工
web -> ser: 提交派工信息
ser -> gcs: 短信提醒派工信息
ser --> web: 派工成功,待领工
web --> zg: 派工成功,等待工程师领工
alt 工程师长时间不领工 或 维修失败申请重新派工
    alt 催促领工
        zg -> web: 催促工程师领工
        web -> ser: 提交工程师领工催促
        ser -> gcs: 短信催促工程师领工
        ser -> web: 催促成功,待领工
        web -> zg: 催促成功,等待工程师领工
    else 重新派工
        zg -> web: 报修重新派工
        web -> ser: 获取当前设备(品牌,类型,规格)可负责维护的设备科工程师列表
        web <-- ser: 设备科工程师列表数据
        web -> web: 显示当前可用工程师列表
        zg -> web: 重新选择派工工程师
        zg -> web: 填写重派原因
        zg -> web: 确认重派
        web -> ser: 请求更换报修的派工信息
        ser -> gcs: 短信提醒派工取消
        ser -> gcso: 短信提醒派工信息
        ser --> web: 重派成功,待领工
        web --> zg: 重派成功,等待工程师领工
    end
end
@enduml