@startuml
participant 设备科工程师 as gcs
participant 微信小程序 as wx
participant 服务器 as ser
participant 科室用户 as usr

gcs->wx: 查看我的维修列表
wx->ser: 获取工程师维修列表
ser-->wx: 维修列表数据
wx->wx: 显示维修列表数据
gcs->wx: 选择维修信息
gcs->wx: 查看设备维修相关信息
gcs->wx: 点击领工按钮
wx->ser: 提交工程师领工信息
ser-->wx: 领工成功
wx-->gcs: 领工成功,请尽快前往维修
@enduml