@startuml
start
:设备科工程师前往科室确认报修问题;
if (报修问题是否如实存在) then (yes)
else (no)
    :填写报修取消说明;
    :科室用户取消报修;
    stop
endif
:确认科室设备报修问题;
if (设备是否在保修期限内) then (yes)
    :向厂商报修设备问题;
    :厂商派遣工程师维修;
    :登记派遣工程师信息;
    repeat
    :厂商工程师进行维修;
    if (厂商工程师表明是否维修成功) then (yes)
    else (no)
        :返回 <厂商派遣工程师维修> 步骤;
        detach
    endif
    repeat while (科室用户检查是否维修成功) is (no)
    ->yes;
    :确认维修完成;
    :维修服务评价;
else (no)
    :设备科工程师检查设备问题;
    if (能否检查出设备存在的问题) then (yes)
        repeat
        :设备科工程师进行设备维修;
        while (是否需要更换配件) is (yes)
            if (是否为高价配件(价格范围可配置)) then (yes)
                :填写设备维修高价配件申购单;
                if (审批是否通过) then (no)
                    :尝试继续维修
                    因配件申购失败导致维修失败
                    申请设备报废;
                    detach
                    elseif (配件价格是否超过5W) then (yes)
                        :将5W元以上配件更换上报卫计委审批;
                        if (审批是否通过) then (no)
                            :尝试继续维修
                            因配件申购失败导致维修失败
                             申请设备报废;
                            detach
                        else (no)
                    endif
                else (no)
                endif
            else (no)
            endif
            :[配件采购];
            :维修单登记更换配件信息;
            :设备科工程师继续维修;
        endwhile
        if (设备科工程师表明是否维修成功) then (no)
            :维修失败申请重新派工;
            :<维修进度回到派工阶段>;
             detach
        else (yes)
        endif
        repeat while (科室用户检查是否维修成功) is (no)
        :确认维修完成;
        :维修服务评价;
    else (no)
        :查询可用维修公司列表;
        :询问维修公司维修报价;
        repeat
            repeat
            :选择维修公司负责维修;
            :提交审批;
            repeat while (是否审批通过) is (no)
            ->yes;
            :与维修公司签订合同;
            :创建维修公司维修单;
            :维修公司首次派人来维修;
            while (是否需要更换配件) is (yes)
                if (是否为高价配件(价格范围可配置)) then (yes)
                    :填写设备维修高价配件申购单;
                    if (审批是否通过) then (no)
                        :尝试继续维修
                        因配件申购失败导致维修失败
                        申请设备报废;
                        detach
                    elseif (配件价格是否超过5W) then (yes)
                        :将5W元以上配件更换上报卫计委审批;
                        if (审批是否通过) then (no)
                            :尝试继续维修
                            因配件申购失败导致维修失败
                            申请设备报废;
                            detach
                        else (yes)
                        endif
                    endif
                else (no)
                endif
                if (授权维修公司购置配件) then (yes)
                    :维修公司负责提供配件;
                else (no)
                    :[配件采购];
                endif
                :维修单登记更换配件信息;
                :联系维修公司派遣工程师继续维修(提供住宿和出行费用);
                :维修公司再次派人来维修;
            endwhile
            if (维修公司工程师表明是否维修成功) then (yes)
            else (no)
                :按照签订合同处理维修失败问题;
            endif
        repeat while (科室用户检查是否维修成功) is (no (重新选择维修公司维修))
        ->yes;
        :确认维修完成;
        fork
            repeat
            :按照签订合同核算维修成功后维修服务费用,填入维修公司维修单;
            :核算维修公司工程师的额外住宿和出行费用,填入维修公司维修单;
            :提交维修公司维修单;
            :由设备科审批维修单;
            repeat while(审批通过) is (no)
            ->yes;
            :生成维修公司维修验收单并由相关领导签字确认;
            :维修公司持维修验收单到财务处进行维修费转账;
            detach
        fork again
            :维修服务评价;
        endfork
    endif
endif
:设备科工程师填写维修报告;
->维修结束;
stop
@enduml