-- 国家食品药品监督管理局 因请求参数加密 暂时无法爬取数据
-- TODO: http://app1.sfda.gov.cn/datasearch/face3/base.jsp?tableId=27&tableName=TABLE27&title=%BD%F8%BF%DA%C6%F7%D0%B5&bcId=118103063506935484150101953610
CREATE TABLE `medical_device_registration_certificate` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updatedAt` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `isEnable` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否可用：0-不可用，1-可用',
  `nameCn` varchar(64) NOT NULL COMMENT '产品名称(中文)',
  `nameEn` varchar(64) NULL COMMENT '产品名称(英文)',
  `no` varchar(64) NOT NULL COMMENT '注册证编号',
  `registrantName` varchar(64) NULL COMMENT '注册人名称',
  `registrantAddress` varchar(128) NULL COMMENT '注册人住所',
  `productionAddress` varchar(128) NULL COMMENT '生产地址',
  `agentName` varchar(64) NULL COMMENT '代理人名称',
  `agemtAddress` varchar(64) NULL COMMENT '代理人住所',
  `model` text NULL COMMENT '型号、规格',
  `structure` text NULL COMMENT '结构及组成',
  `usage` varchar(512) NULL COMMENT '适用范围',
  `otherInfo` text NULL COMMENT '其他内容',
  `remark` varchar(512) NULL COMMENT '备注',
  `approvalAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '批准日期',
  `expiredAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '有效期至',
  `standard` varchar(256) NULL COMMENT '产品标准',
  `changedAt` timestamp NULL COMMENT '变更日期',
  `postcode` varchar(16) NULL COMMENT '邮编',
  `ivdStructure` varchar(512) NULL COMMENT '主要组成成分（体外诊断试剂）',
  `ivdUsage` varchar(512) NULL COMMENT '预期用途（体外诊断试剂）',
  `ivdStore` varchar(512) NULL COMMENT '产品储存条件及有效期（体外诊断试剂）',
  `licenseAuthority` varchar(128) NULL COMMENT '审批部门',
  `changedInfo` text NULL COMMENT '变更情况',
  `originCountryCn` varchar(64) NULL COMMENT '生产国或地区（中文）',
  `originCountryEn` varchar(128) NULL COMMENT '生产国或地区（英文）',
  `manufacturerName` varchar(64) NULL COMMENT '生产厂商名称（中文）',
  `serviceAgent` varchar(64) NULL COMMENT '售后服务机构',
  PRIMARY KEY (`id`)
) COMMENT '医疗器械注册证';