CREATE TABLE `export_task` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updatedAt` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `isEnable` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否可用：0-不可用，1-可用',
  `receivedAt` timestamp NULL COMMENT '任务接手时间',
  `finishedAt` timestamp NULL COMMENT '任务完成时间',
  `status` int NOT NULL default 0 COMMENT '任务状态: 0-队列中 1-处理中 2-待上传 3-导出成功 4-导出失败',
  `type` int NOT NULL COMMENT '导出类型: 0-模板导出 1-JSON导出 2-系统导出',
  `argsJson` MEDIUMTEXT NOT NULL COMMENT '导出请求参数: 根据类型决定 JSON存储',
  `resultJson` text NULL COMMENT '导出返回结果(一般为UploadRecord 对象)',
  `resultSize` int NULL COMMENT '导出结果文件大小(单位byte)',
  `name` varchar(128) NOT NULL COMMENT '任务名称',
  `companyId` varchar(36) NOT NULL COMMENT '任务创建人公司id',
  `creatorId` varchar(36) NOT NULL COMMENT '任务创建人id',
  `creatorName` varchar(64) NOT NULL COMMENT '任务创建人名称',
  `remark` varchar(256) NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) COMMENT '导出任务';

CREATE TABLE `export_template` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updatedAt` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `isEnable` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否可用：0-不可用，1-可用',
  `isDefault` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否默认模板：0-非默认，1-默认',
  `isSystem` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否系统模板：0-用户模板，1-系统模板',
  `name` varchar(128) NULL COMMENT '模板名称',
  `type` varchar(64) NOT NULL default 'USER_DEFINED' COMMENT '模板类型: USER_DEFINED-用户定义 ...',
  `file` text NOT NULL COMMENT '模板文件内容',
  `argsFormatJson` text NULL COMMENT '模板参数格式 JSON格式存储',
  `fileSuffix` varchar(32) NOT NULL COMMENT '文件后缀',
  `companyId` varchar(36) NULL COMMENT '所属公司id',
  `companyName` varchar(64) NULL COMMENT '所属公司名称',
  `departmentId` varchar(36) NULL COMMENT '所属部门id',
  `departmentName` varchar(64) NULL COMMENT '所属部门名称',
  `creatorId` varchar(36) NULL COMMENT '创建人id',
  `creatorName` varchar(64) NULL COMMENT '创建人名称',
  `remark` varchar(256) NULL COMMENT '备注',
  PRIMARY KEY (`id`)
) COMMENT '导出模板';