CREATE TABLE `procurement_detail` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updatedAt` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `isEnable` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否可用：0-不可用，1-可用',
  `classification` int NOT NULL COMMENT '类别:0-医疗设备 1-医用耗材 2-设备配件',
  `typeId` varchar(36) NOT NULL COMMENT '类型id',
  `typeName` varchar(128) NOT NULL COMMENT '类型名称',
  `manufacturer` varchar(64) NULL COMMENT '生产厂商',
  `nativeOrigin` varchar(128) NULL COMMENT '原生产地',
  `specification` varchar(128) NOT NULL COMMENT '规格',
  `model` varchar(64) NULL COMMENT '型号',
  `count` int NOT NULL COMMENT '数量',
  `expectedPrice` decimal(14,2) NULL COMMENT '预计单价',
  `actualPrice` decimal(14,2) NULL COMMENT '实际单价',
  `sumPrice` decimal(14,2) NULL COMMENT '合计金额',
  `guaranteeTime` int NULL COMMENT '保修期限(单位:月)',
  `capitalSource` int NOT NULL COMMENT '资金来源',
  `departmentId` varchar(36) NOT NULL COMMENT '申请人科室id',
  `departmentName` varchar(36) NOT NULL COMMENT '申请人科室名称',
  `applicantId` varchar(36) NOT NULL COMMENT '申请人id',
  `applicantName` varchar(36) NOT NULL COMMENT '申请人姓名',
  `status` int default 0 NOT NULL COMMENT '状态:0-待进行采购 1-采购进行中 2-已完成采购 3-已取消',
  `procurementId` varchar(36) NULL COMMENT '采购项目id',
  `productId` varchar(36) NULL COMMENT '供应商设备产品id',
  `companyId` varchar(36) NOT NULL COMMENT '采购方公司id',
  `applicationId` varchar(36) NOT NULL COMMENT '申请id',
  `applicationType` varchar(36) NOT NULL COMMENT '申请类型编码',
  `contentJson` text NULL COMMENT '采购详情的特殊内容 JSON存储',
  PRIMARY KEY (`id`)
) COMMENT '采购项目详情';

CREATE TABLE `procurement` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updatedAt` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `isEnable` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否可用：0-不可用，1-可用',
  `name` varchar(36) NOT NULL COMMENT '采购项目名称',
  `budget` decimal(14,2) NOT NULL COMMENT '采购预算',
  `method` int NOT NULL COMMENT '采购方式: 0-委托招标 1-自行招标 2-询价方式 3-单一来源 4-竞争性谈判',
  `creatorId` varchar(36) NOT NULL COMMENT '采购项目创建人id',
  `documentJson` text NULL COMMENT '采购流程文档记录, 根据不同的采购方式不同 JSON存储',
  `sellerCompanyName` varchar(64) NULL COMMENT '中标人/成交供应商名称',
  `contentsJson` text NULL COMMENT '装箱内容物清单(包含商业验收相关参数)',
  `packagesJson` text NULL COMMENT '货运包装及内容(包含商业验收相关参数)',
  `purchaserCompanyId` varchar(36) NOT NULL COMMENT '采购方公司id',
  `status` int NOT NULL DEFAULT 0 COMMENT '采购项目状态: 0-选择待采购项 1-采购流程记录 2-双方合同签订 3-产品信息登记 4-商品货物配送 5-项目商业验收 6-项目技术验收 7-项目款项结算-发票登记 8-项目款项结算-余款结算 9-采购项目结项',
  `type` int NULL COMMENT '采购项目类型: 0-医疗设备采购 1-医用耗材采购 2-设备配件采购',
  `commercialCheckStatus` int NOT NULL DEFAULT 0 COMMENT '商业验收状态: 0-待验收 1-验收通过 2-验收失败 3-无须验收',
  `technologyCheckStatus` int NOT NULL DEFAULT 0 COMMENT '技术验收状态: 0-待验收 1-验收通过 2-验收失败 3-无须验收',
  `checkRecordJson` text NULL COMMENT '验收记录(商业验收与技术验收相关参数)',
  `checkReportPhotocopy` text NULL COMMENT '验收报告签字盖章后 拍摄或扫描图片 上传',
  `salespersonName` varchar(36) NULL COMMENT '销售负责人姓名',
  `salespersonIDCard` varchar(128) NULL COMMENT '销售负责人身份证',
  `salespersonIDCardPhotocopy` text NULL COMMENT '销售负责人身份证复印件(加盖公章)',
  `isCanceled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已取消：0-正常，1-取消',
  `cancellationReasonId` varchar(36) NULL COMMENT '取消原因id',
  PRIMARY KEY (`id`)
) COMMENT '采购项目';
