CREATE TABLE `supplier_card` (
  `id` varchar(36) NOT NULL COMMENT '主键',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updatedAt` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `isEnable` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否可用：0-不可用，1-可用',
  `nameCn` varchar(64) NOT NULL COMMENT '中文名',
  `nameEn` varchar(128) NULL COMMENT '英文名',
  `logo` text NULL COMMENT '图标',
  `website` text NULL COMMENT '网站url',
  `country` varchar(4) NOT NULL DEFAULT 'CN' COMMENT '国家编号',
  `cityIndex1` varchar(32) NULL COMMENT '地址索引一级(省)',
  `cityIndex2` varchar(32) NULL COMMENT '地址索引二级(市)',
  `cityIndex3` varchar(32) NULL COMMENT '地址索引三级(区)',
  `cityIndex4` varchar(32) NULL COMMENT '地址索引四级(街)',
  `cityIndex5` varchar(32) NULL COMMENT '地址索引五级(备)',
  `addressPrefix` varchar(128) NULL COMMENT '地址前缀',
  `addressDetail` varchar(128) NULL COMMENT '详细地址',
  `postalCode` varchar(16) NULL COMMENT '邮政编码',
  `hotline` varchar(64) NULL COMMENT '服务热线',
  `lever` int NOT NULL default 0 COMMENT '级别',
  `isAuth` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否认证',
  `isLock` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否锁定',
  `status` int NOT NULL default 0 COMMENT '状态: 0-正常',
  `contactJson` text NOT NULL COMMENT '联系方式:{company:{}, person:[{}]}',
  `slideshow` text NULL COMMENT '轮播图',
  `businessScopeJson` varchar(64) NOT NULL default '[]' COMMENT '营业范围:[0,1,2..]',
  `descriptionInfo` varchar(36) NULL COMMENT '公司简介',
  `serviceProcessInfo` varchar(36) NULL COMMENT '服务流程',
  `qualificationInfo` varchar(36) NULL COMMENT '资质说明',
  `configJson` varchar(256) NOT NULL default '{}' COMMENT '名片配置信息:{}',

  `currentId` varchar(36) NULL COMMENT '当前名片id 对名片进行修改时使用',
  `applicationId` varchar(36) NULL COMMENT '申请id',
  `creatorCompanyId` varchar(36) NOT NULL COMMENT '创建人公司id',
  `creatorCompanyName` varchar(36) NOT NULL COMMENT '创建人公司名称',
  PRIMARY KEY (`id`)
) COMMENT '供应商名片';